OnlineShop/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

OnlineShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.DAO;
using Models.EF;
using OnlineShop.Common;
using OnlineShop.Controllers;
using OnlineShop.Models;
namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            ViewBag.Slides = new SlideDao().ListAll();
            var productDao = new ProductDao();
            ViewBag.NewProducts = productDao.ListNewProduct(8);
            ViewBag.NewProductss = productDao.ListNewProduct1(1);
            ViewBag.ListFeatureProducts = productDao.ListFeatureProduct(8);
            return View();
        }
        //Menu chinh
        [ChildActionOnly]
        public ActionResult MainMenu()
        {
            var model = new MenuDao().ListByGroupID(1);
            return PartialView(model);
        }
        //Menu Top
        [ChildActionOnly]
        public ActionResult TopMenu()
        {
            var model = new MenuDao().ListByGroupID(2);
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult HeaderCart()
        {
            var cart = Session[CommonConstants.CartSession];
            var list = new List<CartItem>();
            if(cart!=null)
            {
                list = (List<CartItem>)cart;
            }
            return PartialView(list);
        }
        //Footer
        [ChildActionOnly]
        public ActionResult Footer()
        {
            var model = new FooterDao().GetFooter();
            return PartialView(model);
        }
    }
}

OnlineShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Dao;
using Models.DAO;
using PagedList;
using PagedList.Mvc;
namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/

        public ActionResult Index()
        {
            var productDao = new ProductDao();
            ViewBag.NewProducts = productDao.ListNewProduct(4);
            ViewBag.ListFeatureProducts = productDao.ListFeatureProduct(4);
            return View();
        }
        [ChildActionOnly]
        public PartialViewResult ProductCategory()
        {
            var model = new ProductCategoryDao().ListAll();
            return PartialView(model);
        }
        [ChildActionOnly]
        public PartialViewResult DMCategory()
        {
            var model = new CategoryDao().ListAll1();
            return PartialView(model);
        }

        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }        
        //Phan trang danh sach san pham
        public ActionResult Category(long cateId, int page = 1, int pageSize = 4)
        {            
            var category = new CategoryDao().ViewDetail(cateId);
            ViewBag.Category = category;
            int totalRecord = 0;
            var model = new ProductDao().ListProductPaging(cateId, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            //Math.Ceiling lam tron len
            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }
        public ActionResult Category1(long cateId, int page = 1, int pageSize = 4)
        {
            var category = new CategoryDao().ViewDetail1(cateId);
            ViewBag.Category = category;
            int totalRecord = 0;
            var model = new ContentDao().ListProductPaging1(cateId, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int totalPage = 0;
            //Math.Ceiling lam tron len
            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }
        //tìm kiếm
        public ActionResult Search(string keyword, int page = 1, int pageSize = 1)
        {
            int totalRecord = 0;
            var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }
        public ActionResult Detail(long cateId)
        {
            var product = new ProductDao().ViewDetail(cateId);
            ViewBag.Category = new ProductCategoryDao().ViewDetail(product.CategoryID.Value);            
            ViewBag.RelatedProducts = new ProductDao().ListRelatedProducts(cateId);
            return View(product);
        }
        public ActionResult Detail1(long cateId)
        {
            var content = new ContentDao().GetByID(cateId);
            ViewBag.Category = new CategoryDao().ViewDetail1(content.CategoryID.Value);
            ViewBag.RelatedProducts = new ContentDao().ListRelatedProducts(cateId);
            ViewBag.User = new UserDao().ViewDetail(cateId);
            return View(content);
        }



    }
}

OnlineShop/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Trang Chủ";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var slides = (List<Models.EF.Slide>)ViewBag.Slides;
	var listNewProducts = (List<Models.EF.Product>)ViewBag.NewProducts;
	var listNewProductss = (List<Models.EF.Product>)ViewBag.NewProductss;
	var listFeatureProducts = (List<Models.EF.Product>)ViewBag.ListFeatureProducts;
}
<!--Link javascrip-->
@*<script src="~/Scripts/jquery-1.8.0.min.js"></script>*@
<script src="~/Scripts/jquery.signalR-1.0.0.min.js"></script>
<script src="@Url.Content("~/signalr/hubs")"></script>
<script>
	$(function () {
		var counterhub = $.connection.counterHub;
		$.connection.hub.start().done(function () {
		});

		counterhub.client.updatecounter = function (count) {
			$("#counter").text(count);
		}
	});
</script>
<br />

@section slide
{

	<div class="header_slide">
		<div class="header_bottom_left">
			<div class="categories">
				<!--Menu-->
				@{ Html.RenderAction("ProductCategory", "Product");}
				
			</div>
		</div>
		<div class="header_bottom_right">
			<!--Slide-->
			<div class="slider">
				<div id="slider">
					<div id="mover" style="top: 20px;">
						@foreach (var item in slides)
						{
							foreach (var item1 in listNewProductss)
							{
								var url = "/chi-tiet/" + item1.MetaTitle + "-" + item1.ID;

								<div id="slide-1" class="slide">
									<div class="slider-img" style="margin-left:80px;margin-right:10px;margin-bottom:35px;">
										<a href="@url"><img src="@item.Image" alt="tìm hiểu thêm" width="500" height="350"></a>
									</div>
									<div class="slider-text">
										<h1><font style="vertical-align: inherit;"><span><font style="vertical-align: inherit;color:red;">HOT</font></span><font style="vertical-align: inherit;color:red;">SALE</font></font><br><span><font style="vertical-align: inherit;"></font></span></h1>
										<h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">GIẢM GIÁ 20%</font></font></h2>
										<div class="features_list">
											<h4><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"></font>@item.Description</font></h4>
										</div>
										<button type="button" class="button" style="background-color:blue;"><a href="@url" style="color:white;">Mua ngay</a></button>
									</div>
									<div class="clear"></div>
								</div>

							}
						}
					</div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
}
<!--Sản Phẩm Mới-->
<div class="content">
	<div class="content_top" style="background:#3fbd3e">
		<div class="heading">
			<h3>Sản Phẩm Mới</h3>
		</div>
		<div class="clear"></div>
	</div>
	<div class="container">
		<div class="row">
			<div class="section group">
				@foreach (var item in listNewProducts)
				{
					var url = "/chi-tiet/" + item.MetaTitle + "-" + item.ID;
					<div class="col-md-3">
						<div class="thumbnail">
							<div class="caption">
								<h4>@item.Name</h4><br />
								<p>@item.Description</p><br /><br />
								<p>
									<a href="@url" class="btn btn-danger" rel="tooltip" title="" data-original-title="Xem chi tiết">Xem</a> <a href="/them-gio-hang?productId=@item.ID&quantity=1" class="btn btn-success" rel="tooltip" title="" data-original-title="Mua hàng">Mua</a>
								</p>
							</div> <a href="@url"><img src="@item.Image" alt="@item.Name" class="grid_1_of_4 images_1_of_4" /></a>
						</div>
					</div>
				}
			</div>
		</div>
	</div>
	<!--Sản phẩm bán chạy-->
	<div class="content_bottom" style="background:#3fbd3e">
		<div class="heading">
			<h3>Sản Phẩm Bán Chạy</h3>
		</div>
		<div class="see">
		</div>
		<div class="clear"></div>
	</div>
	<div class="container">
		<div class="row">
			<div class="section group">
				@foreach (var item in listFeatureProducts)
				{
					var url = "/chi-tiet/" + item.MetaTitle + "-" + item.ID;
					<div class="col-md-3">
						<div class="thumbnail">
							<div class="caption">
								<h4>@item.Name</h4><br />
								<p>@item.Description</p><br /><br />
								<p>
									<a href="@url" class="btn btn-danger" rel="tooltip" title="" data-original-title="Xem chi tiết">Xem</a> <a href="/them-gio-hang?productId=@item.ID&quantity=1" class="btn btn-success" rel="tooltip" title="" data-original-title="Mua hàng">Mua</a>
								</p>
							</div>
							<a href="@url"><img src="@item.Image" alt="@item.Name" /></a>
						</div>
					</div>
				}
			</div>

		</div>
	</div>

</div>
<!--Khách hàng Online-->
<div class="container">
	<button type="button" class="btn btn-primary">Khách hàng Online <span class="badge"> <strong id="counter" class="text"></strong></span></button>
</div>
<!--Css-->
<style type="text/css">
	.thumbnail {
		position: relative;
		overflow: hidden;
	}

	.caption {
		position: absolute;
		top: 0;
		right: 0;
		background: rgba(66, 139, 202, 0.75);
		width: 100%;
		height: 100%;
		padding: 2%;
		display: none;
		text-align: center;
		color: #fff !important;
		z-index: 2;
	}

	.text {
		font-weight: bold;
		color: blue;
		font-size: 20px;
	}
</style>
<!--Javascrip-->
<script type="text/javascript">
	$(document).ready(function () {
		$("[rel='tooltip']").tooltip();
		$('.thumbnail').hover(
			function () {
				$(this).find('.caption').slideDown(250); //.fadeIn(250)
			},
			function () {
				$(this).find('.caption').slideUp(250); //.fadeOut(205)
			}
		);
	});
</script>

<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<script>
	window.fbAsyncInit = function () {
		FB.init({
			xfbml: true,
			version: 'v7.0'
		});
	};

	(function (d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>