OnlineShop/Areas/Admin/Controllers/FooterController.cs
using Models.DAO;
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class FooterController : BaseController
    {
        //
        // GET: /Admin/Footer/

        public ActionResult Index()
        {
            return View();
        }
        [HashCredential(RoleID = "EDIT_CONTENT")]
        public ActionResult Select(string searchString, int page = 1, int pageSize = 10)
        {
            var dao = new FooterDao();
            var model = dao.ListAllPaging(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }
        [HttpGet] 
        public ActionResult Create()
        {
            //SetViewBag();
            return View("Create");
        }



        [HttpPost]
        public ActionResult Create(Footer footer)
        {
            if (footer.Content != null)
            {
                if (ModelState.IsValid)
                {
                    var dao = new FooterDao();
                    var session = (Common.UserLogin)Session[OnlineShop.Common.CommonConstants.USER_SESSION];
                    footer.Content = footer.Content;
                    footer.Status = footer.Status;
                    string id = dao.Insert(footer);
                }

            }
            return View("Create");
        }


        public ActionResult Edit(int id)
        {
            //SetViewBag();
            var footer = new FooterDao().ViewDetail(id);
            return View(footer);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Footer footer)
        {
            if (ModelState.IsValid)
            {
                var dao = new FooterDao();
                var session = (Common.UserLogin)Session[OnlineShop.Common.CommonConstants.USER_SESSION];
                footer.Content = footer.Content;
                footer.Status = footer.Status;
                var result = dao.Update(footer);
                if (result)
                {
                   
                    return RedirectToAction("Select", "Footer");
                }
                else
                {
                  //  ModelState.AddModelError("", "Cập nhật không thành công");
                    ModelState.AddModelError("", StaticResources.Resources.Updatefailed);
                }
            }
            return View("Select");
        }

    }
}

OnlineShop/Areas/Admin/Controllers/ProductCategoryController.cs
using Common;
using Models.DAO;
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class ProductCategoryController : BaseController
    {
        //
        // GET: /Admin/ProductCategory/
        OnlineShopDbContext db = new OnlineShopDbContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Select(string searchString, int page = 1, int pageSize = 5)
        {
            var dao = new ProductCategoryDao();
            var model = dao.ListAllPaging(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }
        [HttpGet] //  truyen viewbag len view them san pham
        public ActionResult Create()
        {
            SetViewBag();
            return View("Create");
        }



        [HttpPost] // them san pham
        public ActionResult Create(ProductCategory pdcategory)
        {
            if (pdcategory.Name != null)
            {
                if (ModelState.IsValid)
                {
                    var dao = new ProductCategoryDao();
                    pdcategory.MetaTitle = pdcategory.MetaTitle;

                    pdcategory.CreatedDate = DateTime.Now;
                    var session = (Common.UserLogin)Session[OnlineShop.Common.CommonConstants.USER_SESSION];
                    pdcategory.CreatedBy = session.UserName;
                    pdcategory.MetaKeywords = pdcategory.MetaTitle;
                    pdcategory.MetaDescriptions = pdcategory.MetaTitle;

                    long id = dao.Insert(pdcategory);
                    if (id > 0)
                    {

                     //   SetAlert("Thêm loại sản phẩm thành công", "success");
                        SetAlert(StaticResources.Resources.Addsuccessfulproductcategories, "success");

                        return RedirectToAction("Select", "ProductCategory");
                    }
                    else
                    {
                      //  ModelState.AddModelError("", "Thêm sản phẩm không thành công");
                        ModelState.AddModelError("", StaticResources.Resources.Addproducttypefailed);
                    }
                }

            }
            SetViewBag();
            // SetAlert("Thêm sản phẩm  không thành công", "success");
          //  SetAlert("Tên sản phẩm bắt buộc", "error");
            SetAlert(StaticResources.Resources.Requiredproductname, "error");
            return View("Create");
        }


        public ActionResult Edit(int id)
        {
            SetViewBag();
            var pdproduct = new ProductCategoryDao().ViewDetail(id);
            return View(pdproduct);
        }

        [HttpPost]
        public ActionResult Edit(ProductCategory pdproduct)
        {
            if (ModelState.IsValid)
            {
                var dao = new ProductCategoryDao();
                var session = (Common.UserLogin)Session[OnlineShop.Common.CommonConstants.USER_SESSION];
                pdproduct.Name = pdproduct.Name;
                pdproduct.MetaTitle = pdproduct.MetaTitle;
                pdproduct.CreatedBy = session.UserName;
                pdproduct.ModifiedBy = session.UserName;

                var result = dao.Update(pdproduct);
                if (result)
                {
                 //   SetAlert("Cập nhật loại sản phẩm thành công", "success");
                    SetAlert(StaticResources.Resources.Updateproducttypesuccessfully, "success");
                    return RedirectToAction("Select", "ProductCategory");
                }
                else
                {
                 //   ModelState.AddModelError("", "Cập nhật không thành công");
                    ModelState.AddModelError("", StaticResources.Resources.Updatefailed);
                }
            }
            SetViewBag();
            return View("Select");
        }


        [HttpDelete] // xoa san pham
        public ActionResult Delete(int id)
        {
            new ProductCategoryDao().Delete(id);
         //   SetAlert("Xoá thành công", "success");
            SetAlert(StaticResources.Resources.Deletesuccessful, "success");
            return RedirectToAction("Index");
        }

        // viewbag truyen dropdownlist category
        public void SetViewBag(long? selectedId = null)
        {
            var dao = new CategoryDao();
            ViewBag.CategoryID = new SelectList(dao.ListAll(), "ID", "Name", selectedId);
        }
    }
}

OnlineShop/Controllers/UserController.cs
using Models.DAO;
using Models.EF;
using OnlineShop.Models;
using System;
using System.Configuration;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BotDetect.Web.Mvc;
using OnlineShop.Common;
using System.Xml.Linq;
using System.Text.RegularExpressions;
using System.Text;
using Facebook;


namespace OnlineShop.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult Login()
        {

            return View();
        }

        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }

        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }

        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
              
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.first_name + " " + me.last_name;
                string userName = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;

                var user = new User();
                user.Email = email;
                user.UserName = email;
                user.Status = true;
                user.Name = firstname + " " + middlename + " " + lastname;
                user.CreatedDate = DateTime.Now;
                var resultInsert = new UserDao().InsertForFacebook(user);
                if (resultInsert > 0)
                {
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.ID;
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                }
            }
            return Redirect("/");
        }


        [HttpPost]
       // [CaptchaValidation("CaptchaCode", "registerCaptcha", "Mã xác nhận không đúng!")]

        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                if (dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (dao.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else
                {
                    var user = new User();
                    user.UserName = model.UserName;
                    user.Password = Encryptor.MD5Hash(model.Password);
                    user.GroupID = "MEMBER";
                    user.Phone = model.Phone;
                    user.Email = model.Email;
                    user.Name = model.Name;
                    user.Address = model.Address;
                    user.CreatedDate = DateTime.Now;
                    user.Status = true;
                    if (!string.IsNullOrEmpty(model.ProvinceID))
                    {
                        user.ProvinceID = int.Parse(model.ProvinceID);
                    }
                    if (!string.IsNullOrEmpty(model.DistrictID))
                    {
                        user.DistrictID = int.Parse(model.DistrictID);
                    }

                    var result = dao.Insert(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công";
                        model = new RegisterModel();        
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công!");
                       
                    }
                }
            }
            return View(model);
        }
      
        public JsonResult LoadProvince()
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~/assets/client/data/Provinces_Data.xml"));

            var xElements = xmlDoc.Element("Root").Elements("Item").Where(x => x.Attribute("type").Value == "province");
            var list = new List<ProvinceModel>();
            ProvinceModel province = null;
            foreach (var item in xElements)
            {
                province = new ProvinceModel();
                province.ID = int.Parse(item.Attribute("id").Value);
                province.Name = item.Attribute("value").Value;
                list.Add(province);

            }
            return Json(new
            {
                data = list,
                status = true
            });
        }

        public JsonResult LoadDistrict(int provinceID)
        {
            var xmlDoc = XDocument.Load(Server.MapPath(@"~/assets/client/data/Provinces_Data.xml"));

            var xElement = xmlDoc.Element("Root").Elements("Item")
                .Single(x => x.Attribute("type").Value == "province" && int.Parse(x.Attribute("id").Value) == provinceID);

            var list = new List<DistrictModel>();
            DistrictModel district = null;
            foreach (var item in xElement.Elements("Item").Where(x => x.Attribute("type").Value == "district"))
            {
                district = new DistrictModel();
                district.ID = int.Parse(item.Attribute("id").Value);
                district.Name = item.Attribute("value").Value;
                district.ProvinceID = int.Parse(xElement.Attribute("id").Value);
                list.Add(district);

            }
            return Json(new
            {
                data = list,
                status = true
            });
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var result = dao.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.ID;
                    Session.Add(CommonConstants.USER_SESSION, userSession);
                    return Redirect("/");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhập không đúng.");
                }
            }
            return View(model);
        }

        public ActionResult Logout()
        {
            Session[CommonConstants.USER_SESSION] = null;
            return Redirect("/");
        }

    }
}

OnlineShop/Views/Shared/DMCategory.cshtml
@model List<Models.EF.Category>
<div class="categories">
	<ul class="p-3 mb-2 bg-danger text-white">
		<h3 style="background-color:blue;">Chăm sóc khách hàng</h3>
		@foreach (var item in Model.Where(x => x.ParentID == null))
		{
			var child = Model.Where(x => x.ParentID == item.ID);
			var parentClass = child.Count() > 0 ? "class =dropdown-toggle data-toggle=dropdown" : "";
			<li class="dropdown">
				<a class="dropdown-toggle" style="font-weight:bold;" data-toggle="dropdown" togg style="text-decoration:none" href="/tin-tuc1/@item.MetaTitle-@item.ID" @parentClass>@item.Name</a>
				@if (child.Count() > 0)
				{
					<ul class="dropdown-menu">
						@foreach (var childItem in child)
						{
							<li><a style="font-weight:bold;" href="/tin-tuc1/@childItem.MetaTitle-@childItem.ID">@childItem.Name</a></li>
						}

					</ul>
				}
			</li>

		}
	</ul>
</div>

OnlineShop/Views/Shared/Footer.cshtml
<link href="~/assets/client/phone/phone.css" rel="stylesheet" />


<script>
	$(document).ready(function () {
		$('.user-support').click(function (event) {
			$('.social-button-content').slideToggle();
		});
	});
</script>
<style>
	#fa {
		background: rgba(71, 88, 245, 1);
	}
</style>
<div class="social-button">
	<div class="social-button-content">
		<a href="tel:0379850845" class="call-icon" rel="nofollow">

			<img src="~/assets/client/images/phone-square-alt-solid.svg" width="35px" height="35px" />
			@*<i class="fa fa-whatsapp" aria-hidden="true"></i>*@
			<div class="animated alo-circle"></div>
			<div class="animated alo-circle-fill "></div>
			<span>Hotline: 0384190358</span>
		</a>
		<a href="sms:0379850845" class="sms">
			<img src="~/assets/client/images/sms-solid.svg" id="sms" width="35px" height="35px" />
			@*<i class="fa fa-weixin" aria-hidden="true"></i>*@
			<span>SMS: 0384190358 </span>
		</a>
		<a href="https://www.facebook.com" class="mes">
			<img src="~/assets/client/images/facebook-square-brands.svg" id="fa" width="35px" height="35px"/>
			@*<i class="fa fa-facebook-square" aria-hidden="true" id="fa"></i>*@
			<span>Nhắn tin Facebook</span>
		</a>

	</div>

	<a class="user-support" data-original-title>
		<img src="~/assets/client/images/info-solid.svg" width="35px" height="35px"/>
		@*<i class="fa fa-user" aria-hidden="true"></i>*@
		<div class="animated alo-circle"></div>
		<div class="animated alo-circle-fill "></div>
	</a>
</div>


@model Models.EF.Footer
@Html.Raw(Model.Content)

OnlineShop/Views/Shared/HeaderCart.cshtml
@model List<OnlineShop.Models.CartItem>
<div class="cart">
    <p>
        <span> <a style="text-decoration: none;" href="/gio-hang"> <img src="https://img.icons8.com/clouds/100/000000/favorite-cart.png" width="100"/><div class="clear"></div></a></span><div id="dd" class="wrapper-dropdown-2">
           @Model.Count Sản Phẩm
            <ul class="dropdown">
                <li>Bạn có @Model.Count sản phẩm trong giỏ hàng</li>
                @foreach(var item in Model)
                {
                    <li>@item.Product.Name (@item.Quantity)</li> 
                }
            </ul>
        </div>
    </p>
</div>

OnlineShop/Views/Shared/Index.cshtml
@model Models.EF.Contact
@{
    ViewBag.Title = "Liên Hệ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #mapCanvas {
        height: 600px;
    }
</style>
@section jsFooter{
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="/assets/client/js/controller/contactController.js"></script>
    <script>
        function initMap() {
            var uluru = { lat: 21.046300, lng: 105.793266 };
            var map = new google.maps.Map(document.getElementById('mapCanvas'), {
                zoom: 18,
                center: uluru
            });

            var contentString = '@Html.Raw(Model.Content)';

            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            var marker = new google.maps.Marker({
                position: uluru,
                map: map,
                title: 'Địa chỉ'
            });
            marker.addListener('click', function () {
                infowindow.open(map, marker);
            });
        }
        google.maps.event.addDomListener(window, 'load', initMap);
    </script>
}
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6">
                <h2>Thông tin liên hệ</h2>
                @Html.Raw(Model.Content) 

                <br />
                <h2>Gửi thông tin</h2>
                <form>
                    <div class="form-group">
                        <label>Họ tên</label>
                        <input type="text" id="txtName" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Điện thoại</label>
                        <input type="text" id="txtMobile" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Địa chỉ</label>
                        <input type="text" id="txtAddress" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" id="txtEmail" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label>Yêu cầu</label>
                        <textarea id="txtContent" class="form-control"></textarea>
                    </div>
                    <button id="btnSend" class="btn btn-success">Gửi đi</button>
                </form>
            </div>
            <div class="col-md-6">
                <h2>Bản đồ</h2>
                <div class="map" id="mapCanvas"></div>
            </div>
        </div>
    </div>
</div>

OnlineShop/Views/Shared/MainMenu.cshtml
@model List<Models.EF.Menu>
<div class="menu">
	<ul class="navbar-nav">
		@foreach (var item in Model)
		{
			<li class="nav-item"><a  class="nav-link" style="text-decoration:none;border-right: 2px ridge #0d9c9c;" href="@item.Link" target="@item.Target">@item.Text</a></li>
		}
		<div class="clear"></div>
	</ul>
</div>

OnlineShop/Views/Shared/ProductCategory.cshtml
@model List<Models.EF.ProductCategory>
<div class="categories">
    <ul class="p-3 mb-2 bg-info text-white">
        <h3 style="background:#e71a1a">Danh mục sản phẩm</h3>
        @foreach (var item in Model.Where(x => x.ParentID == null))
        {
            var child = Model.Where(x => x.ParentID == item.ID);
            var parentClass = child.Count() > 0 ? "class =dropdown-toggle data-toggle=dropdown" : "";
            <li class="dropdown" style="display:block">
                <a class="dropdown-toggle" style="font-weight:bold;  " data-toggle="dropdown" togg style="text-decoration:none" href="/san-pham/@item.MetaTitle-@item.ID" @parentClass>@item.Name</a>
                @if (child.Count() > 0)
                {
                    <ul class="dropdown-menu">
                        @foreach (var childItem in child)
                        {
                            <li><a style="font-weight:bold;" href="/san-pham/@childItem.MetaTitle-@childItem.ID">@childItem.Name</a></li>
                        }

                    </ul>
                }
            </li>


        }
    </ul>
</div>
<!--CSS menu danh mục-->
<style>
    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-menu {
        display: none;
        position: absolute;
        right: 0;
        background-color: #e9d8f4;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

    .dropdown-menu a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

        .dropdown-menu a:hover {
            background-color: #58257b;
            color: white;
        }

    .dropdown:hover .dropdown-menu {
        display: block;
    }

    .dropdown:hover  {
        background-color:#23efb7;
    }
</style>

OnlineShop/Views/Shared/TopMenu.cshtml
@model List<Models.EF.Menu>

<div class="account_desc">
    @{
        var session = (OnlineShop.Common.UserLogin)Session[OnlineShop.Common.CommonConstants.USER_SESSION];
    }
    @if (session == null)
    {
        <ul>
            @foreach (var item in Model)
            {
                <li><a href="@item.Link" target="@item.Target"><button type="button" class="btn btn-primary">@item.Text</button></a></li>
            }

        </ul>
    }
    else
    {
        <ul>
            <li>Xin chào:@session.UserName</li>
            <li>@Html.ActionLink("Thoát", "Logout", "User")</li>
        </ul>
    }

</div>
<div class="clear"></div>

OnlineShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>BookStore - Mua sắm online - Thoả sức lựa chọn</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="shortcut icon" type="image/png" href="~/assets/client/images/lg.png" />
	<link href="/assets/client/css/bootstrap.css" rel="stylesheet" />
	<link href="/assets/client/css/bootstrap-theme.css" rel="stylesheet" />
	<link href="/assets/client/css/boostrap-social.css" rel="stylesheet" />
	<!--bootstrap slide châm ngôn-->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">

	<link href="/assets/client/css/jquery-ui.css" rel="stylesheet" />
	<link href="/assets/client/css/font-awesome.min.css" rel="stylesheet" />
	<link href="~/assets/fontawesome/css/fontawesome.min.css" rel="stylesheet" />
	<link href="/assets/client/css/slider.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/assets/client/css/style.css" rel="stylesheet" />
	<link href="~/assets/client/css1/css/fontawesome.min.css" rel="stylesheet" />
	<link href="~/assets/client/phone/phone.css" rel="stylesheet" />
	<link href="~/assets/client/phone/phone1.css" rel="stylesheet" />
	<!-- Latest compiled and minified JavaScript -->
	<script src="/assets/client/js/jquery-1.11.3.min.js"></script>
	<script src="/assets/client/js/jquery-ui.js"></script>
	<script src="/assets/client/js/bootstrap.min.js"></script>
	<script src="~/assets/client/js/JavaScript.js"></script>
	<script type="text/javascript" src="/assets/client/js/move-top.js"></script>
	<script type="text/javascript" src="/assets/client/js/easing.js"></script>
	<script type="text/javascript" src="/assets/client/js/startstop-slider.js"></script>
	<!--slide Châm ngôn-->
	<script src="~/Scripts/jquery-1.11.1.min.js"></script>
	<script>
		$('#myCarousel').carousel({
			interval: 4000
		});
	</script>
</head>
<body>
	<nav class="navbar navbar-expand-sm bg-dark">
		<div class="wrap">
			<div class="header">
				<!--Menu top-->
				<div class="headertop_desc">
					@{Html.RenderAction("TopMenu", "Home");}
				</div>
				<div class="header_top">
					<div class="logo">
						<!--logo-->
						<a href="/" ref="nofollow"><img src="~/assets/client/images/logo/icons8-book-100.png" class="img-fluid" width="175" height="175" /></a>
						<!--banner-->
						<img src="~/assets/client/images/banner/bannerbook.png" class="img-fluid" alt="Responsive image" width="650" height="175">
					</div>
					<!--Gio hang-->
					@{Html.RenderAction("HeaderCart", "Home");}
					<script type="text/javascript">
						function DropDown(el) {
							this.dd = el;
							this.initEvents();
						}
						DropDown.prototype = {
							initEvents: function () {
								var obj = this;

								obj.dd.on('click', function (event) {
									$(this).toggleClass('active');
									event.stopPropagation();
								});
							}
						}

						$(function () {

							var dd = new DropDown($('#dd'));

							$(document).click(function () {

								$('.wrapper-dropdown-2').removeClass('active');
							});

						});

					</script>
					<div class="clear"></div>
				</div>
				<!--Menu chinh-->
				<div class="header_bottom" style="background:#3fbd3e">
					<div class="menu">
						<ul>
							@{Html.RenderAction("MainMenu", "Home");}
						</ul>
					</div>
					<!--Tim kiem-->
					<div class="search_box">
						<form class="form-inline my-2 my-lg-0" action="/tim-kiem" method="get">
							<input type="text" value="Nhập tên sản phẩm" name="keyword" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
							<input type="submit" value="">
						</form>
					</div>
					<div class="clear"></div>
				</div>
				<!--Slide-->
				@RenderSection("slide", required: false)

			</div>
			<div class="main">
				@RenderBody()
			</div>
		</div>
	</nav>
	

	<!--Footer-->
	<div class="footer">

		<!-- Your customer chat code -->
		<div class="fb-customerchat" style="margin-bottom:100px"
			 attribution=setup_tool
			 page_id="108132274238380"
			 theme_color="#0084ff"
			 logged_in_greeting="Chào mừng bạn đến với BOOK STORE. Chúng tôi có thể giúp gì cho bạn?"
			 logged_out_greeting="Chào mừng bạn đến với BOOK STORE. Chúng tôi có thể giúp gì cho bạn?">
		</div>
		<script lang="javascript">
            var __vnp = { code: 1089, key: '', secret: '7b268d2234705113d1b734f25a01e35e' };
            (function () {
                var ga = document.createElement('script');
                ga.type = 'text/javascript'; ga.async = true; ga.defer = true;
                ga.src = '//core.vchat.vn/code/tracking.js';
                var s = document.getElementsByTagName('script'); s[0].parentNode.insertBefore(ga, s[0]);
            })();
		</script>

		@{Html.RenderAction("Footer", "Home");}
	</div>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>
	<script type="text/javascript">
		$(document).ready(function () {
			$().UItoTop({ easingType: 'easeOutQuart' });

		});
	</script>

	<a href="#" id="toTop"><span id="toTopHover"> </span></a>

	<script src="/assets/client/js/controller/baseController.js"></script>
	@RenderSection("jsFooter", required: false)


</body>
</html>