OnlineShop/Areas/Admin/Controllers/FeedBackController.cs
using Models.DAO;
using Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class FeedBackController : BaseController
    {
        OnlineShopDbContext db = new OnlineShopDbContext();

        public ActionResult Index()
        {
            return View();
        }

        // xem san pham. co phan trang 
        public ActionResult Select(string searchString, int page = 1, int pageSize = 10)
        {
            var dao = new FeedBackDao();
            var model = dao.ListAllPaging(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }


        
        [HttpDelete] 
        public ActionResult Delete(int id)
        {
            new FeedBackDao().Delete(id);
            return RedirectToAction("Index");
        }

    }
}

OnlineShop/Areas/Admin/Views/FeedBack/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

@section header{
    Trang Phản Hồi
}

OnlineShop/Areas/Admin/Views/FeedBack/Select.cshtml
@model PagedList.IPagedList<Models.EF.Feedback>
@using PagedList.Mvc;
@{
	ViewBag.Title = "Quản lý Menu";
	Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}
@section header{
	<span class="abel label-info" style="color:white;">THÔNG TIN PHẢN HỒI</span>
}

@section jsFooter{

	<script src="/assets/admin/js/controller/productController.js"></script>
	<script src="/assets/admin/js/controller/userController.js"></script>

}

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-body">
				@using (Html.BeginForm("Select", "FeedBack", FormMethod.Get))
				{
					<div class="row form-group">
						<div class="col-lg-12">
							<div class="col-md-4">
								<input type="text" value="@ViewBag.SearchString" class="form-control" name="searchString" />
							</div>
							<div class="col-md-4">
								<button type="submit" class="btn btn-success">Tìm kiếm</button>
							</div>
						</div>
					</div>
				}
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr>
								<th>ID</th>
								<th>Tên KH</th>
								<th>Nội dung</th>
								<th>Phone</th>
								<th>Email</th>
								<th>Địa chỉ</th>

								<th>Ngày phản hồi</th>
								<th>Thay đổi</th>

							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
							<tr id="row_@item.ID">
								<td>@item.ID </td>
								<td>@item.Name</td>
								<td>@item.Content</td>
								<td>@item.Phone</td>
								<td>@item.Email</td>
								<td>@item.Address</td>

								<td>@item.CreatedDate</td>
								<td width="200">
									<button class="btn btn-warning">
										<i class="fa fa-trash-o">
											@Ajax.ActionLink("Xoá", "Delete", new { @id = item.ID }, new AjaxOptions
									  {
										  Confirm = "Bạn có muốn xoá?",
										  OnComplete = "$('#row_" + @item.ID + "').remove()",
										  HttpMethod = "Delete"
									  })
										</i>
									</button>
								</td>
							</tr>
							}

						</tbody>
					</table>
					@Html.PagedListPager(Model, page => Url.Action("Select", new { page, @searchString = @ViewBag.SearchString }))
				</div>
				<!-- /.table-responsive -->
			</div>
			<!-- /.panel-body -->
		</div>
	</div>
</div>
<!-- Modal -->